secrets_project/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),

]

secrets_project/secrets_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='ice_cream')),
    path('admin/', admin.site.urls),
]

secrets_project/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

Posts = get_user_model()
Author = get_user_model()


class Authors(models.Model):
    nickname = models.CharField(max_length=50, null=False)
    first_name = models.CharField(max_length=50, null=False)
    last_name = models.CharField(max_length=50, null=False)
    email = models.EmailField(null=False)
    sex = models.CharField(max_length=50, null=False)
    age = models.IntegerField(null=True)


class Posts(models.Model):
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=255)
    author = models.ForeignKey(
        Authors,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='posts'
    )

secrets_project/posts/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    template = 'posts/index.html'
    title = "Главная страница"
    context = {
        'title': title,
        'content': 'Главная страница',
    }
    return render(request,template,context)

secrets_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            блок
        {% endblock %}
    </title>
</head>
<body>
  {% include 'includes/header.html' %}
  <div>
      {% block content %}
          блок
      {% endblock %}
  </div>
  {% include 'includes/footer.html' %}
</body>
</html>

secrets_project/templates/includes/footer.html
{% load static %}
<div>
    <h1>
        footer
    </h1>
</div>

secrets_project/templates/includes/header.html
{% load static %}
<div>
    <ul style="display: inline">
        <li>
            <a href="{% url 'posts:index' %}">
                <img src="img/logo.png" alt="Girl in a jacket" width="50" height="50">
            </a>
        </li>
        <li>
            <h1>
                 header
            </h1>
        </li>
    </ul>
</div>

secrets_project/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  {{ content }}
{% endblock %}